// src/components/InputComponent.tsx
import React from 'react';

interface InputComponentProps {
  label: string;
  value: number;
  disabled?: boolean;
  type?: string;
  placeholder?: string;
  step?: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

const InputComponent: React.FC<InputComponentProps> = ({
  label,
  value,
  disabled = false,
  type = "text",
  placeholder = "",
  step = "",
  onChange
}) => {
  return (
    <div>
      <label className="block font-bold">{label}:</label>
      <input
        className={`h-6 border-b w-full focus:outline-none ${disabled ? 'bg-gray-300 border-red-500' : 'border-green-500'}`}
        value={value}
        onChange={onChange}
        disabled={disabled}
        type={type}
        placeholder={placeholder}
        step={step}
      />
    </div>
  );
};

export default InputComponent;

// src/components/InputComponent.vue
<template lang="pug">
div
  label.block.font-bold {{label}}:
  input.h-6.border-b.w-full(
    :value="value"
    class="focus:outline-none"
    :class="disabled ? 'bg-gray-300 border-red-500' : 'border-green-500'"
    @input="$emit('input', $event.target.value)"
    :disabled="disabled"
    :type="type"
    :placeholder="placeholder"
    :step="step"
  )
</template>

<script>
export default {
  props: {
    label: String,
    value: Number,
    disabled: Boolean,
    type: String,
    placeholder: String,
    step: String,
  }
}
</script>
