// src/components/SelectComponent.vue
<template lang="pug">
div
  label.block.font-bold {{label}}:
  select.h-6.border-b.w-full(
    :value="value"
    class="focus:outline-none"
    :class="disabled ? 'bg-gray-300 border-red-500' : 'border-green-500'"
    @input="$emit('input', $event.target.value)"
    :disabled="disabled"
  )
    option(
      v-for="(option, index) in options"
      :value="index"
    ) {{option}}
</template>

<script>
export default {
  props: {
    label: String,
    value: Number,
    disabled: Boolean,
    options: Array,
  }
}
</script>

// src/components/SelectComponent.tsx
import React from 'react';

interface SelectComponentProps {
  label: string;
  value: number;
  disabled?: boolean;
  options: string[];
  onChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
}

const SelectComponent: React.FC<SelectComponentProps> = ({
  label,
  value,
  disabled = false,
  options,
  onChange
}) => {
  return (
    <div>
      <label className="block font-bold">{label}:</label>
      <select
        className={`h-6 border-b w-full focus:outline-none ${disabled ? 'bg-gray-300 border-red-500' : 'border-green-500'}`}
        value={value}
        onChange={onChange}
        disabled={disabled}
      >
        {options.map((option, index) => (
          <option key={index} value={index}>
            {option}
          </option>
        ))}
      </select>
    </div>
  );
};

export default SelectComponent;
